package coderunner;

import static dgir.dialect.builtin.BuiltinOps.ProgramOp;

import blockly.dgir.compiler.java.CompilationResult;
import blockly.dgir.compiler.java.JavaCompiler;
import components.VmManagedComponent;
import core.Game;
import core.utils.logging.DungeonLogger;
import dgir.vm.api.DapServerUtils;
import dgir.vm.dap.DapServer;
import java.io.IOException;
import org.jetbrains.annotations.Nullable;
import server.Server;

/**
 * This class is used to run Java code generated by the Blockly language. It compiles the code
 * dynamically.
 *
 * <p>It uses the Java Compiler API to compile the code and then uses reflection to execute it. The
 * code is executed in a separate thread to avoid blocking the main thread. The class also provides
 * methods to check if the code is currently running and to stop the execution of the code.
 *
 * <p>This class is a singleton, meaning that there is only one instance of it in the application.
 *
 * @see Server Server
 */
public class BlocklyCodeRunner {
  private static final DungeonLogger LOGGER = DungeonLogger.getLogger(BlocklyCodeRunner.class);
  private static BlocklyCodeRunner instance;

  private final DapServer dapServer;

  private static final String baseCode =
"""
import Dungeon.Direction;
import Dungeon.Hero;
import Dungeon.IO;
import Dungeon.ItemType;
import Dungeon.LevelElement;
import Dungeon.Arrays;

public class Main {
  %s
}
""";

  // private constructor for singleton
  private BlocklyCodeRunner() {
    dapServer = DapServerUtils.createServer();
    try {
      dapServer.start();
    } catch (IOException e) {
      throw new RuntimeException("Failed to start DAP server", e);
    }
    DebugPauseBridge.install(dapServer);
  }

  /**
   * Returns the instance of the BlocklyCodeRunner.
   *
   * @return The instance of the BlocklyCodeRunner.
   */
  public static BlocklyCodeRunner instance() {
    synchronized (BlocklyCodeRunner.class) {
      if (instance == null) {
        instance = new BlocklyCodeRunner();
      }
    }
    return instance;
  }

  /**
   * Returns {@code true} while the VM that was started by the last {@link #compileAndRunCode} call
   * is still executing.
   *
   * @return {@code true} if the VM thread is alive
   */
  public boolean isRunning() {
    return dapServer.isVmRunning();
  }

  /**
   * Requests the current program to stop and interrupts the VM thread so any blocking wait inside
   * an op runner is unblocked immediately. Only call from main thread.
   *
   * <p>This is a no-op when nothing is running.
   */
  public void stopExecution() {
    if (dapServer.isVmRunning()) {
      dapServer.stopVm();
      while (dapServer.isVmRunning()) {
        try {
          Thread.sleep(10);
        } catch (InterruptedException e) {
          throw new RuntimeException(e);
        }
      }
    }
    // Remove the vm managed components from the player. These might not be removed as they
    // might rely on a
    // vm operation to finish execution and thus might not be removed in time. This can lead
    // to issues when the player is teleported to another level while vm operations are still
    // pending.
    Game.player()
        .ifPresent(
            e ->
                e.componentStream()
                    .filter(VmManagedComponent.class::isInstance)
                    // Make sure we have a copy of the components before iterating over them.
                    // Otherwise, the iterator might change during removal.
                    .toList()
                    .forEach(c -> ((VmManagedComponent) c).destroyVmManagedComponent()));
  }

  /**
   * Compiles and runs the given code. If the code is not a complete program, it will be wrapped in
   * a main method and a class.
   *
   * @param code the code to run
   * @param isCompleteProgram whether the code is a complete program or not.
   * @param waitForDebugger whether to wait for a debugger to attach before running the code.
   * @param sourceFileName the name of the source file.
   */
  public void compileAndRunCode(
      String code,
      boolean isCompleteProgram,
      boolean waitForDebugger,
      @Nullable String sourceFileName) {
    compileAndRunCode(code, 0, isCompleteProgram, waitForDebugger, sourceFileName);
  }

  /**
   * Compiles and runs the given code. If the code is not a complete program, it will be wrapped in
   * a main method and a class. Only call from main thread.
   *
   * @param code the code to run
   * @param sleepAfterEachLine the time to sleep after executing each line of code, in milliseconds.
   * @param completeProgram whether the code is a complete program or not.
   * @param waitForDebugger whether to wait for a debugger to attach before running the code.
   * @param sourceFileName the name of the source file.
   */
  public void compileAndRunCode(
      String code,
      int sleepAfterEachLine,
      boolean completeProgram,
      boolean waitForDebugger,
      @Nullable String sourceFileName) {
    String completeCode;
    if (!completeProgram) {
      completeCode = String.format(baseCode, code);
    } else {
      completeCode = code;
    }
    LOGGER.info(
        "Compiling and running code: \n"
            + completeCode
            + "for file: "
            + sourceFileName
            + " with sleep: "
            + sleepAfterEachLine
            + " and waitForDebugger: "
            + waitForDebugger);
    CompilationResult compilationResult =
        JavaCompiler.compileSource(
            completeCode, sourceFileName != null ? sourceFileName : "Main.java");
    if (compilationResult instanceof CompilationResult.Failure failure) {
      throw new RuntimeException(failure.toString());
    }
    ProgramOp program = ((CompilationResult.Success) compilationResult).program();
    try {
      dapServer.reloadProgram(program, waitForDebugger);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
