plugins {
    id 'java-library'
    alias(libs.plugins.errorprone)
}

sourceSets.main.java.srcDirs = ['src/']
sourceSets.main.resources.srcDirs = ['assets/']

sourceSets.test.java.srcDirs = ['test/']
sourceSets.test.resources.srcDirs = ['test_assets/']

dependencies {
    api libs.commons.lang3
    api 'tools.jackson.core:jackson-databind:3.0.3'
    implementation 'guru.nidi:graphviz-java-all-j2v8:0.18.1'
    implementation 'org.eclipse.collections:eclipse-collections-api:13.0.0'
    implementation 'org.eclipse.collections:eclipse-collections:13.0.0'
    api libs.jetbrains.annotations

    errorprone libs.errorprone.core

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.register('testDgirAndVm', Test) {
    group = 'verification'
    description = 'Runs both :dgir:test and :dgir:vm:test.'
    dependsOn ':dgir:test', ':dgir:vm:test'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        events 'passed', 'skipped', 'failed'
    }
}

repositories {
    mavenCentral()
}
